# Nixpacks configuration for Playwright service

[phases.setup]
# Install system dependencies needed for Playwright browsers
aptPkgs = [
    "libnss3",
    "libnspr4",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "libxrandr2",
    "libgbm1",
    "libxkbcommon0",
    "libpango-1.0-0",
    "libcairo2",
    "libasound2",
    "libatspi2.0-0",
    "libgtk-3-0",
    "libdrm2",
    "libx11-6",
    "libxcb1",
    "libxext6",
    "libxss1",
    "libxtst6"
]

[phases.install]
# Install npm dependencies and Playwright browsers
cmds = [
    "npm ci",
    "npx playwright install chromium"
]

[start]
# Start the service
cmd = "npm start"